spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/rye?serverTimezone=UTC&characterEncoding=utf8
      username: root
      # 测试类RyeApplicationTests中运行encrypt()方法获取加密密码和公钥,此加密密码为:root123456
      password: l860zR8+SX1DYJ2mVfA1LWC1d7N9z+zP52oF++oGrdHPDtCR+FGqJHuoLw+CCJtUjMb0SCZFDX+k122zSP+GNg==
      # 数据库密码解密公钥
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMoPLX5Wj2EuVFoQagCGR/pZINNLq6EQ9axwiHPoIVPrHc+GWo1qlTnkv8mm9wJyEtomwxndwEWrPd3ZqhS8THECAwEAAQ==
      filters: config
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${spring.datasource.druid.public-key}

springdoc:
  swagger-ui:
    # swagger ui默认访问路径: http://localhost:8088/swagger-ui/index.html
    # 若需自定义swagger ui访问路径,则增加springdoc.swagger-ui.path配置
    # 开启swagger ui界面
    enabled: true
  api-docs:
    # api-docs路径：即swagger ui显示api信息时获取数据的访问路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.puhj.rye.controller.api

mybatis-plus:
  configuration:
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
