springdoc:
  swagger-ui:
    # 配置swagger ui访问路径为: http://localhost:8088/swagger-ui/index.html
    path: /index.html
    # 开启swagger ui界面
    enabled: true
  api-docs:
    # api-docs路径：即swagger ui显示api信息时获取数据的访问路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: com.puhj.rye.controller.api

mybatis-plus:
  configuration:
    # 控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
