spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rye?serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource

# 生产环境禁用springdoc
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
