spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

jwt:
  # jwt token签名
  secret: rye
  # token令牌有效时长(单位:秒)
  expired-time: 7200

files:
  # 上传路径为项目路径下的res/upload
  path: "res/upload"

logging:
  config: classpath:config/logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
